export enum DEVICE_TYPE {
  MOBILE_S = "MOBILE_S",
  MOBILE_M = "MOBILE_M",
  MOBILE_L = "MOBILE_L",
  TABLET_S = "TABLET_S",
  TABLET_M = "TABLET_M",
  TABLET_L = "TABLET_L",
  LAPTOP = "LAPTOP",
  DESKTOP = "DESKTOP",
  DESKTOP_HORIZONTAL = "DESKTOP_HORIZONTAL",
  TV = "TV",
  TV_4K = "TV_4K",
  MOBILE_VERTICAL = "MOBILE_VERTICAL",
  MOBILE_HORIZONTAL = "MOBILE_HORIZONTAL",
  TABLET_VERTICAL = "TABLET_VERTICAL",
  TABLET_HORIZONTAL = "TABLET_HORIZONTAL",
}

export const BREAKPOINTS = {
  MOBILE_S_MAX_WIDTH: 380,
  MOBILE_MAX_WIDTH: 480,
  TABLET_S_MAX_WIDTH: 834,
  TABLET_M_MAX_WIDTH: 1024,
  TABLET_L_MAX_WIDTH: 1366,
  LAPTOP_MAX_WIDTH: 1400,
  DESKTOP_MAX_WIDTH: 1920,
  TV_MAX_WIDTH: 3840,
} as const;
